accounts/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.views import (
	LoginView, 
	LogoutView,
	PasswordResetView,
	PasswordResetDoneView,
	PasswordResetConfirmView,
	PasswordResetCompleteView,
	)
app_name = 'accounts'
urlpatterns = [
	
	path('login/', LoginView.as_view(template_name = 'accounts/login.html'), name = 'login'),
	path('logout/', LogoutView.as_view(template_name = 'accounts/logout.html'), name = 'logout'),
	path('register/', views.register, name = 'register'), 
	path('profile/', views.view_profile, name = 'view_profile'),
	path('profile/<int:pk>/', views.view_profile, name = 'view_profile_with_pk'),
	path('profile/edit', views.edit_profile, name = 'edit_profile'),
	path('change-password/', views.change_password, name = 'change_password'),

	path('reset-password/', PasswordResetView.as_view(
		template_name = 'accounts/reset_password.html',
		email_template_name="accounts/password_reset_email.html",
		success_url = reverse_lazy('accounts:password_reset_done'),
		), name = 'reset_password'),

	path('reset-password/done/', PasswordResetDoneView.as_view(template_name = 'accounts/password_reset_done.html',), name = 'password_reset_done'),
	path('reset-password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',success_url=reverse_lazy('accounts:password_reset_complete')),name = 'password_reset_confirm'),
	path('reset-password/complete', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name = 'password_reset_complete' ),
	]

home/urls.py
from django.urls import path, re_path
from home.views import HomeView
from .import views

app_name = 'home'

urlpatterns =[
	path('', HomeView.as_view(), name = 'home'),
	path('connect/<slug:operation>/<int:pk>/', views.change_friends, name='change_friends')
]

tutorial/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from tutorial import views

urlpatterns = [
	path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')), 
    path('home/', include('home.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import  User
from django.db.models.signals import post_save

class UserProfileManager(models.Manager):
	def  get_queryset(self):
		return super(UserProfileManager, self).get_queryset().filter(city='Brooklyn')


class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete =models.CASCADE)
	description = models.CharField(max_length = 100, default = '')
	city = models.CharField(max_length = 100, default='')
	website = models.URLField(max_length = 100, default='')
	phone = models.IntegerField(default=0)
	image = models.ImageField(upload_to='profile_image', blank=True)

	Brooklyn = UserProfileManager()
	objects = models.Manager()

	def __str__(self):
		return self.user.username

def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
	"""docstring for Post"""
	post = models.CharField(max_length = 500)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	created = models.DateTimeField(auto_now_add = True)
	updated = models.DateTimeField(auto_now = True)

	def __str__(self):
		return self.post


class Friend(models.Model):
	users = models.ManyToManyField(User)
	current_user = models.ForeignKey(User, related_name='owner', null=True, on_delete=models.PROTECT)

	@classmethod
	def make_friend(cls, current_user, new_friend):
		friend, created = cls.objects.get_or_create(
			current_user = current_user
			)
		friend.users.add(new_friend)


	@classmethod
	def lose_friend(cls, current_user, new_friend):
		friend, created = cls.objects.get_or_create(
			current_user = current_user
			)
		friend.users.remove(new_friend)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm


class RegistrationFrom(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = (
			'username', 
			'first_name',
			'last_name',
			'email',
			'password1',
			'password2'
			)

	def save(self,commit=True):
		user = super(RegistrationFrom, self).save(commit=False)
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.email = self.cleaned_data['email']

		if commit:
			user.save()

		return user

class EditProfileForm(UserChangeForm):

	class Meta:
		model = User
		fields = (
			'email',
			'first_name',
			'last_name',
			'password',
			)

home/forms.py
from django import forms
from home.models import Post

class HomeForm(forms.ModelForm):
	post = forms.CharField(widget = forms.TextInput(
		attrs = {
		'class': 'form-control',
		'placeholder': 'Write your post here...'
		}
		))

	class Meta:
		model = Post 
		fields = (
			'post',
			)

accounts/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from accounts.forms import (
	RegistrationFrom, 
	EditProfileForm
	)
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, authenticate,login




def register(request):
	if request.method =='POST':
		form = RegistrationFrom(request.POST)
		if form.is_valid():
			form.save()
			username = request.POST.get('username')
			password = request.POST.get('password1')
			user = authenticate(
				request=request,
				username=username,
				password=password
				)
			login(request, user)
			return redirect(reverse('home:home'))
	else:
		form = RegistrationFrom()

	args = {'form': form}
	return render(request, 'accounts/reg_form.html', args)


def view_profile(request, pk=None):
	storage = messages.get_messages(request)
	if pk:
		user = User.objects.get(pk=pk)
	else:
		user = request.user
	args = {'user':user, 'messages':storage}
	return render(request, 'accounts/view_profile.html', args)


def edit_profile(request):
	if request.method =='POST':
		form = EditProfileForm(request.POST, instance=request.user)

		if form.is_valid():
			form.save()
			return redirect(reverse('accounts:view_profile'))

	else:
		form = EditProfileForm(instance=request.user)

	args = {'form': form}
	return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)

		if form.is_valid():
			form.save()
			messages.success(request, 'Your password has been changed successfully')
			update_session_auth_hash(request, form.user)
			return redirect(reverse('accounts:view_profile'))

	else:
		form = PasswordChangeForm(user=request.user)

	args = {'form': form}
	return render(request, 'accounts/change_password.html', args)
	

home/views.py
from django.views.generic import TemplateView
from home.forms import HomeForm
from home.models import Post,Friend
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

class HomeView(TemplateView):
	template_name = 'home/home.html'

	def get(self, request):
		form = HomeForm()
		posts = Post.objects.all().order_by('-created')
		users = User.objects.exclude(id = request.user.id)
		friend, created = Friend.objects.get_or_create(current_user=request.user)
		friends = friend.users.all()

		args = {'form':form, 'posts':posts, 'users':users, 'friends':friends}
		return render(request, self.template_name, args)

	def post(self, request):
		form = HomeForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.user = request.user
			post.save()

			text = form.cleaned_data['post']
			form = HomeForm()
			return redirect('home:home')

		args = {'form': form, 'text': text}
		return render(request, self.template_name, args)

def change_friends(request, operation, pk):
	new_friend = User.objects.get(pk=pk)
	if operation == 'add':
		Friend.make_friend(request.user, new_friend)
	elif operation =='remove':
		Friend.lose_friend(request.user, new_friend)
	return redirect('home:home')


# Create your views here.

tutorial/views.py
from django.shortcuts import redirect
from django.urls import reverse

def login_redirect(request):
	return redirect(reverse('accounts:login'))
	

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html>
<head>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,500,500i,700,800i" rel="stylesheet">
  <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
	{% block head %}
	{% endblock %}
</head>
<body>
  
	 <nav class="navbar navbar-expand-sm   navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" class="nav-link" href="/">Social Network</a>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:home' %}">Home</a>
            </li>
            
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:view_profile' %}">Profile</a>
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:edit_profile' %}">Edit</a>
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:change_password' %}">Change-Password </a>
            </li>
            
          </ul>
          </div>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo03" >
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
        </ul>
    </div>
          {% else %}
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
           
               <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:reset_password' %}">Reset-Password</a>
            </li>
        </ul>
    </div>
    {% endif %}
      </nav>
      <div class="container">
	{% block body %}
	{% endblock %}
  </div>
</body>
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>

accounts/templates/accounts/change_password.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
{% endblock %}


{% block body %}
<br>
<h1>Change Password</h1>
		<form method="post">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-danger btn-sm" type="submit" name="button">
			Submit
		</button>
		</form>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
{% endblock %}


{% block body %}

<h1>Edit</h1>
		<form method="post">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-danger btn-sm" type="submit" name="button">
			Submit
		</button>
		</form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
{% endblock %}


{% block body %}
			<h1>
			Welcome
		</h1>
		<h5>Vadakam, Namaste, Bojure !!</h5>
		<br>
		<form method="post">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-danger btn-sm" type="submit" name="button">
			Login
		</button>
		</form>
	
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
{% endblock %}


{% block body %}
	
		<h2>Logged out</h2>
		<p>See you soon</p>
	
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
{% endblock %}


{% block body %}
			<h1>
			Password reset complete
		</h1>
		<p>Your password has been set. You may go ahead and log in now.</p>
			<p><a href="{% url 'accounts:login' %}">Login</a></p>
		
	
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
{% endblock %}


{% block body %}
			<h1>
			Enter new password
		</h1>
		<p>Please enter your new password twice so we can verify you typed it in correctly.</p>
		<form method="post">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-danger btn-sm" type="submit" name="button">
			Change my password
		</button>
		</form>
	
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
{% endblock %}


{% block body %}
	
		<h1>Password reset sent</h1>
		<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
		<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder</p>
	
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %} 
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %} 

{% trans "Please go to the following page and choose a new password:" %} 
{% block reset_link %} 
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %} 
{% trans 'Your username, in case you’ve forgotten:' %} {{ user.get_username }} 
{% trans "Thanks for using our site!" %} {% blocktrans %}The {{ site_name }} team{% endblocktrans %}
 {% endautoescape %} 

accounts/templates/accounts/reg_form.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
{% endblock %}


{% block body %}
<h1>Register</h1>
		<form method="post">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-danger btn-sm" type="submit" name="button">
			Submit
		</button>
		</form>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
{% endblock %}


{% block body %}
		<h1>Password Reset</h1>
		<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>
		<form method="post">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-danger btn-sm" type="submit" name="button">
			Reset my password
		</button>
		</form>
	
{% endblock %}

accounts/templates/accounts/view_profile.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
	<title>Profile</title>
{% endblock %}


{% block body %}
<h1>Profile</h1>
{% if messages %}
{% for message in messages %}
<div class="alert alert-success" role="alert">
	<center>{{ message }}</center>
</div>
{% endfor %}
{% endif %}
	<p><em>Username: </em>{{ user }}</p>
	<p><em>First Name: </em>{{ user.first_name }}</p>
	<p><em>Last Name: </em>{{ user.last_name }}</p>
	<p><em>Email: </em>{{ user.email }}</p>
	<p><em>Discription: </em>{{ user.userprofile.description }}</p>
	<p><em>City: </em>{{ user.userprofile.city }}</p>
	<p><em>Website: </em>{{ user.userprofile.website }}</p>
	<p><em>Phone: </em>{{ user.userprofile.phone }}</p>
	{% if user.userprofile.image %}
	<img src="{{ user.userprofile.image.url }}" width="250">
	{% endif %}
{% endblock %}

accounts/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        {% block head %}
        <meta charset="utf-8">
        <title>Base</title>
        {% endblock %}
    </head>
    <body>
        <div class="container">

            <!-- Static navbar -->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container">
                  <a class="navbar-brand" href="#">Social Network</a>
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
          
                  <div class="collapse navbar-collapse" id="navbarsExample07">
                    <ul class="navbar-nav mr-auto"> 
                    </ul>
                    {% if user.is_authenticated %}
                    <ul class="nav navbar-nav">
                      <li><a href="/account">Home</a></li>
                      <li><a href="/account/logout">LogOut</a></li>
                      <li><a href="{%url 'accounts:profile'%}">Profile</a></li>
                      <li><a href="/account/profile/edit">Edit</a></li>
                      <li><a href="/account/change-password">Change Password</a></li>
                     
                    </ul>
                    
                    {% else %}
                    <ul class="nav navbar-nav">
                      <li><a href="/account/reset-password">Reset Password</a></li>

                    </ul>
                      <ul class="nav navbar-nav navbar-right">
                          <li><a href="/account/login">LogIn</a></li>
                          <li><a href="/account/register">Register</a></li>
                        </ul>
                   {% endif %}
                  </div>
                </div>
              </nav>
        </div>
      
        {% block body %}
        <h1>Base</h1>
        {% endblock %}
        
    </body>
</html>

home/templates/home/home.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
{% endblock %}

{% block body %}
<div class="row">
<div class="col-md-8">
	<h1>Home</h1>
<form method="POST">
	{% csrf_token %}
	{{ form.post }}
	<br>
	<button class="btn btn-danger btn-sm" type="submit" name="button">
			Submit
		</button>
</form>
<br>
	{% for p in posts %}
	<h5>{{ p.post }}</h5>
	<p class="text-muted">Posted by {{ p.user.get_full_name }} on {{ p.created }}</p>
	{% endfor %}

	
</div>
<div class="clo-md-4">
	<h1>Other People</h1>
	{% for user in users %}
	{% if user not in friends %}
	<a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
	<h5>{{ user.username }}</h5>
</a>
<a href="{% url 'home:change_friends' operation='add' pk=user.pk %}">		<button class="btn btn-success btn-sm" name="button">Add Friend</button>
</a>
{% endif %}
	{% endfor %}
	<h1>Friends</h1>
		{% for friend in friends %}
	<a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
	<h5>{{ friend.username }}</h5>
</a>
<a href="{% url 'home:change_friends' operation='remove' pk=friend.pk %}"><button class="btn btn-danger btn-sm" name="button">Remove Friend</button>
</a>
	{% endfor %}
</div>
</div>
{% endblock %}